### ISSUE TITLE
Picture in Picture shows MainActivity

### ISSUE THREAD

**Issue by PomepuyN** [googlesamples/androidtv-Leanback#100]
Both this project and the leanback showcase have this issue.

## Reproduction

When using the PIP feature, if you completely leave the app and then re-open it from the home screen, the `MainActivity` is displayed in the picture in picture window.
All my tests were done in an emulator running API 26.

## Fix try
The only way I found to avoid that is to put something like that in the player activity manifest entry:
```android:taskAffinity="showcase.player"```

But it also causes other issues:

1. The app is shown twice in the recent list
2. The video controls are not displayed anymore

Is there a ways to manage this case properly?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
