### ISSUE TITLE
Global search not working

### ISSUE THREAD

**Issue by khat33b** [googlesamples/androidtv-Leanback#101]
If you try the Android TV Global Search, no results from this application shows up. I am using API 27. the search path is also different in the app. Android TV uses the `authority/search/search_suggest_query/*` path and not `authority/search_suggest_query`.

**Comment by foxum** [comment]
I found few problems in searchable.xml file and changed this:
```
android:searchSuggestAuthority="com.example.android.tvleanback"
android:searchSuggestPath=""
android:searchSuggestSelection=" ?"
```

Also I removed from AndroidManifest.xml:

`<path-permission
                android:pathPrefix="/search"
                android:readPermission="android.permission.GLOBAL_SEARCH"/>`

And now it works.

**Comment by felislynx-silae** [comment]
Hi there. To be honest global search is not working for me on MiBox with Assistant. It's not working for sample or my application. I can only see "Available on" button, but no results like from youtube or other apps

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
