### ISSUE TITLE
build for android 6.0

### ISSUE THREAD

**Issue by wuqingwei** [googlesamples/androidtv-Leanback#102]
hi，
Is it possible？
Thanks

**Comment by benbaxter** [comment]
What do you mean? Do you want to know if you can set the tartget / compile sdk to 26?

If you revert the [last commit](https://github.com/googlesamples/androidtv-Leanback/commit/b293af92a74e30f96d0d91d8537536a58cfefe3e), the sample should build for android 6.0 as expected.
