### ISSUE TITLE
Is it possible to add the TV Input Service in this sample

### ISSUE THREAD

**Issue by jose-pr** [googlesamples/androidtv-Leanback#104]
Seeing as work on https://github.com/googlesamples/androidtv-sample-inputs seems to have stopped and has not been updated with Exoplayer2 and this app is an example for androidtv, i would to see the addition to this sample of the TV Input Service using exoplayer2. Basically an app that apart from providing it own internal player also offer them as LiveTV. 
Or maybe create a new sample app for the TV Input Service based on Exoplayer2 and other new libs/frameworks.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
