### ISSUE TITLE
PlaybackSeekDataProvider can not seek to zero

### ISSUE THREAD

**Issue by KazumiHARADA** [googlesamples/androidtv-Leanback#109]
Hi.
Our application use PlaybackSeekDataProvider for a seek function, but we cannot seek to position only zero.
Furthermore, sample application that made by Google (android.support.v17.leanback.supportleanbackshowcase) also occurred this error.
This error reproduce way is followings:
1. Play video.
2. Seek to zero.
3. Seek failed, and back before setting the position.

However, The error log on the Logcat is not displayed.

Could you tell us correct way to fix this error.

**Comment by Fleker** [comment]
How are you doing the seek to 0? IIRC the seeking methods are all based around epoch time, the number of seconds since 1970. You'd want to offset your seek position by the time the video started playing.

**Comment by KazumiHARADA** [comment]
Thank you for your reply.
I realized that there are the factor due to this error on PlaybackTransportControlGlue.java.

```
        @Override
        public void onSeekFinished(boolean cancelled) {
            if (!cancelled) {
                if (mLastUserPosition > 0) {  <- here
                    seekTo(mLastUserPosition);
                }
            } else {
                if (mPositionBeforeSeek >= 0) {
                    seekTo(mPositionBeforeSeek);
                }
            }
            mIsSeek = false;
            if (!mPausedBeforeSeek) {
                play();
            } else {
                mPlayerAdapter.setProgressUpdatingEnabled(false);
                // we neeed update UI since PlaybackControlRow still saves previous position.
                onUpdateProgress();
            }
        }
```

However, I can't attach this class. If `if (mLastUserPosition > 0) { ` is `if (mLastUserPosition >= 0) { ` it may be correct way.
I also offset your seek position by the time the video started playing but it couldn't working.
Could you tell me the correct way that how to use `PlaybackTransportControlGlue.java`

**Comment by KazumiHARADA** [comment]
OK, Thank you for your advice.
I'm reporting this issue on the support library's tracker now.
After report the issue, this issue on Github close.

**Comment by KazumiHARADA** [comment]
https://issuetracker.google.com/u/2/issues/72348943

**Comment by benbaxter** [comment]
Thanks for reporting this issue @KazumiHARADA! I cc'd an engineer on the leanback library and updated the bug with steps to reproduce.

**Comment by benbaxter** [comment]
The bug has been fixed and will be in the next version of the support library. 

@KazumiHARADA - Thank you for your research and raising this to our attention! 😄

**Comment by KazumiHARADA** [comment]
You're welcome @benbaxter!
 I'm looking forward to be released it!
Thank you for good work.
