### ISSUE TITLE
Couldn't Work Adaptive bitrate for Protected Drm Contents  .

### ISSUE THREAD

**Issue by Nihar-android** [googlesamples/androidtv-Leanback#111]
hi i am trying to play protected Drm Content but ABR not working . 
gradle : 

    implementation 'com.google.android.exoplayer:exoplayer:2.6.1'
    implementation 'com.google.android.exoplayer:extension-leanback:2.6.1'

code snippet below : 

             TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        mTrackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
        try {

            drmSessionManager = buildDrmSessionManagerV18("https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAABSMKboAAABgby-2Wso9pmC4qz72RnjskZzidUmX7WgyUkE7aJSfg_Fh5Xc7R6YNw6Fo5GMyojEzkoYE2WhOHqYPJzu94ZyN86rBlvzs0u5S996Z6qiNfbJz6IKuLcKr2KgLNalGrIS1SN-lAAYRNqEY4VZb2LZQuk6yUfk");
        } catch (Exception e) {
        }
        @DefaultRenderersFactory.ExtensionRendererMode int extensionRendererMode = DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON;
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(getActivity(), drmSessionManager, extensionRendererMode);
        mPlayer = ExoPlayerFactory.newSimpleInstance(renderersFactory, new DefaultTrackSelector(videoTrackSelectionFactory));

      mPlayerAdapter = new LeanbackPlayerAdapter(getActivity(), mPlayer, UPDATE_DELAY);
        mPlaylistActionListener = new PlaylistActionListener(mPlaylist);
        mPlayerGlue = new VideoPlayerGlue(getActivity(), mPlayerAdapter, mPlaylistActionListener);
        mPlayerGlue.setHost(new VideoFragmentGlueHost(this));
        mPlayerGlue.playWhenPrepared();

**Comment by benbaxter** [comment]
@Nihar-android 

What specifically is not working? Do you have a stacktrace? Did DRM playback work before using the extensions from ExoPlayer 2? 

Can you provide more details?

Thank you!

**Comment by Nihar-android** [comment]
@benbaxter

1 . DRM playback with adaptive is  working  perfectly on mobile and Tablet apps , but  not working in android tv apps where as am  using exoplayer 2 .
2.  It is working like buffering many times .
3. No i didn't have any stacktrace , because it didn't throw any exception . thank you .

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
