### ISSUE TITLE
Variable Column Span on VerticalGridView

### ISSUE THREAD

**Issue by bangoker** [googlesamples/androidtv-Leanback#112]
I want to have a VerticalGridView with cards of different width. Something like this:

```
█ █ █ █
███ ███
█ █ █ █
█████ █
█ █ █ █
```

With regular support libraries, I'm able to use [GridLayoutManager.SpanSizeLookup](https://developer.android.com/reference/android/support/v7/widget/GridLayoutManager.SpanSizeLookup.html) for this scenario.

Leanback seems to have it's own implementation of GridLayoutManager, but it  it doesn't support the `setSpanSizeLookup` method, and even if it did, the manager is set and configured very early in the fragment, so just replacing it with another will cause issues, because it doesn't get configured as expected.

Is there any way to solve this and be able to specify how many columns should each element in the grid take?

**Comment by eduardvasilache** [comment]
@bangoker I am trying to implement something similar. Did you find a solution?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
