### ISSUE TITLE
VideoFragment - Subtitle not showing on Video

### ISSUE THREAD

**Issue by fadzleyhud** [googlesamples/androidtv-Leanback#113]
Hi,
I'm using VideoFragment with Exoplayer 2, I'm able to play Dash video with widevine drm. The question is how to display the subtitle? . Do i need to create a glue component? I have tried look into exoplayer 2 sample but the subtitle still not displaying. Please show me how to display the media subtitle. Thanks

**Comment by acollazomayer** [comment]
@fadzleyhud can you tell me how did you manage to play dash with widevine. THANKS
