### ISSUE TITLE
PlaybackSupportFragment - ControlsOverlay autohide only at onResume()

### ISSUE THREAD

**Issue by vhangiu** [googlesamples/androidtv-Leanback#114]
The PlaybackSupportFragment only autohides if it's resumed. The late PlaybackOverlaySupportFragment was autohiding also after the fade in animation ended or the user stopped interacting with the playback controls. Will the autohide behaviour be readded? Users were pretty much used with the playback controls autohiding.

**Comment by benbaxter** [comment]
Closing as this discussion is related to the leanback library and not necessarily the sample. The sample demonstrates the loss in functionality as leanback upgraded.

Continuing discussion on [Android TV developer's G+ post](https://plus.google.com/u/1/100326514927587049881/posts/MNDfabjYcw9)
