### ISSUE TITLE
not able to build

### ISSUE THREAD

**Issue by nalovma** [googlesamples/androidtv-Leanback#115]
I am not able to build the project anymore after upgrading to the new android studio

**Comment by benbaxter** [comment]
Hi @nalovma, just a few questions.

Did you download a fresh instance of studio or did you upgrade from the beta/canary channel?

Did you update the android-gradle-plugin?

What errors are you receiving in the build logs?

**Comment by nalovma** [comment]
Hi @benbaxter 
I made an upgrade for Android studio, also. update Gradle because it forces me to do the update.
it's a mix of errors. because of some libraries was deprecated

**Comment by benbaxter** [comment]
Hello @nalovma 

Is this only project that does not build for you in Android Studio or are you seeing error for all projects?

I am getting the following error when building in AS 3.1. I also updated the gradle plugin. Is this the same error you are seeing?

"The specified Android SDK Build Tools version (27.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used."

I have updated the gradle files locally and will push an update later.

Out of curiosity, which libraries are deprecated? Some of them are not the latest version but I do not think any of them are deprecated.

**Comment by benbaxter** [comment]
@nalovma I pushed a [commit](https://github.com/googlesamples/androidtv-Leanback/commit/1165ae96fa9da1660abdf9cf3dbd953aec01e2b0) that cleans up the gradle files for AS 3.1 and support libs 27.1.0. Can you test if this resolves your build issues?
