### ISSUE TITLE
Create Category Title List Under ListRow in Leanback

### ISSUE THREAD

**Issue by smojip** [googlesamples/androidtv-Leanback#116]
I want to build a category title list under a row in android TV (leanback) and when select any title change the row Cardviews . I am currently using another row below this row. but when selected this category title row BrowseFragment scrolled to this row and upper row exit out from screen and this is not good for me.

What is the best way to solve this problem?

![stack](https://user-images.githubusercontent.com/16184106/39304586-5f078e9a-496f-11e8-89ec-aa6906d63d61.jpg)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
