### ISSUE TITLE
DRMSessionManager with Leanback-Exoplayer

### ISSUE THREAD

**Issue by jboisjo** [googlesamples/androidtv-Leanback#117]
Hey,

Have you tried a DRM-Widevine stream with this library? There's no example in the sample and also it doesn't work very well.

We have a 2-3 sec freezing issue everytime a new encrypted playlist has been loaded. If i removed the DrmSessionManager on the buildAudioRenderers in RenderersFactory, video plays fine but there's no audio obv.

We we're using only exoplayer with our layouts and everything was smooth.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
