### ISSUE TITLE
android tv leanback VideoPlayer background color

### ISSUE THREAD

**Issue by Alhydra** [googlesamples/androidtv-Leanback#119]
How can I change the background color of the Video player on the leanback library for tv apps.

I have a problem when the it starts playing a movie (usually the size is smaller than the view) it shrinks a leaving a grey background (instead of black) like in the image below.

![screenshot](https://user-images.githubusercontent.com/29724310/40155236-0dd01a06-5982-11e8-80d8-7d125e5756b0.jpg)

**Comment by okycelt** [comment]
If you're using `VideoSupportFragment`, you can just set the background of the root view in either `onCreateView` or `onViewCreated`.

Like this
```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View root = super.onCreateView(inflater, container, savedInstanceState);
    root.setBackgroundResource(android.R.color.black);
    return root;
}
```

or like this
```
@Override
public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    view.setBackgroundResource(android.R.color.black);
}
```

Maybe there's also a way to change by styling, but I'm not sure about that.

**Comment by Alhydra** [comment]
I am actually using the VideoFragment ( no the support), but i'll try it, thank you for your reply I really appreciate it.

**Comment by hellfire1980** [comment]
I wonder is there anyway to remove the top and bottom black bar to make it a full screen?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
