### ISSUE TITLE
In-card video playback?

### ISSUE THREAD

**Issue by bangoker** [googlesamples/androidtv-Leanback#123]
What would be the best practice to have video play inside the RowsFragment cards, and then being able to click on them to make them fullscreen, and continue playback where it was, smoothly.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
