### ISSUE TITLE
Disable google Assintant in app

### ISSUE THREAD

**Issue by niennguyen** [googlesamples/androidtv-Leanback#125]
After update device to android 7. I press mic button, that didn't focus search page. It launches Google Assistant. How to disable Google Assistant in app

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
