### ISSUE TITLE
Picture in picture reverts video aspect ratio to original after animation and goes out of bounds

### ISSUE THREAD

**Issue by eXeeLD** [googlesamples/androidtv-Leanback#126]
Screenshot
https://i.stack.imgur.com/XSGsK.png

In order to reproduce

AndroidManifest.xml
`  <activity android:name=".ui.PlaybackActivity"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:configChanges=
                "screenSize|smallestScreenSize|screenLayout|orientation"/>`

VideoPlayerGlue.java
https://paste.ofcode.org/YNiCzPiaV5XzVYzMjDCGQP

**Comment by eXeeLD** [comment]
Thank you for your reply, i tried with the deprecated function and with the builder(new one), when i insert aspect ratio, only the window changes size, the video does not scale, it remains full screen , in the scalled window(of picture in picture)

**Comment by eXeeLD** [comment]
Fixed it by managing the surface view
 @Override
    public void onPictureInPictureModeChanged(boolean isInPictureInPictureMode, Configuration newConfig) {
        super.onPictureInPictureModeChanged(isInPictureInPictureMode, newConfig);
        hideControlsOverlay(isInPictureInPictureMode);
        SurfaceView surfaceView = getSurfaceView();
        ViewGroup.LayoutParams p = surfaceView.getLayoutParams();
        p.width = dpToPx(newConfig.screenWidthDp);
        p.height = dpToPx(newConfig.screenHeightDp);
        surfaceView.setLayoutParams(p);
    }

**Comment by eXeeLD** [comment]
This results in a video flicker, thus is a bad solution

**Comment by eXeeLD** [comment]
@benbaxter so i finally managed to make picture in picture smoth as baby's but, i had to edit 5 leanback classes, in order to change the surfaceView to a textureView

**Comment by eXeeLD** [comment]
here is described the solution with code
https://stackoverflow.com/questions/51589257/when-entering-picture-in-picture-video-does-not-resize-to-fit-window#51592408

**Comment by benbaxter** [comment]
Entering PIP mode is a configuration change so you might see a flicker. Also, your PIP window is not the same aspect ratio as the video. In those images you supplied, the PIP window is square but the video is a rectangle.

In onPictureInPictureModeChanged(), use the new config to optimize your video for the new size. For TV though, you should only have to hide the controls since the view should maintain the same aspect ratio.

Here is a [commit](https://github.com/googlesamples/androidtv-Leanback/commit/f0d37e4464c1b370bac5e69662dff565fdcc7a69) for PIP (well, removal of PIP) that you can use for reference.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
