### ISSUE TITLE
Problem at display subtitles with leanbackplayeradapter

### ISSUE THREAD

**Issue by cgarcia55** [googlesamples/androidtv-Leanback#127]
I'm using this example, but when I try to show the subtitles of a video, they just do not show, I'm using the following code to add the subtitles:
`Format subtitleFormat = Format.createTextSampleFormat(
                            null, // An identifier for the track. May be null.
                            MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
                            Format.NO_VALUE, // Selection flags for the track.
                            "en"); // The subtitle language.
        DataSource.Factory mediaDataSourceFactory =  new DefaultDataSourceFactory(getActivity(), userAgent);
                    MediaSource subtitleSource =       new SingleSampleMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(Uri.parse("http://45.79.158.247/test.srt"), subtitleFormat, C.TIME_UNSET);
            // Plays the video with the sideloaded subtitle.
                    MergingMediaSource mergedSource =
                            new MergingMediaSource(mediaSource, subtitleSource);`

without success.
Any idea how to show subtitles?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
