### ISSUE TITLE
Changes background color to black few times in RowSupportFragment in FireTV on item selection

### ISSUE THREAD

**Issue by m9jpatidar** [googlesamples/androidtv-Leanback#128]
I am using RowsSupportFragment of lean-back library for my TV application. It changes background color of the fragment to black while selecting items (few times color changes to black where as we have set background color transparent) in FireTV only, whereas same code is working fine in AndroidTV

How i solve this issue please suggest

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
