### ISSUE TITLE
Replace fragment caused RecyclerView$ViewHolder.shouldIgnore()’ on a null object reference

### ISSUE THREAD

**Issue by sophietsentvb** [googlesamples/androidtv-Leanback#129]
Hi, when I try to replace fragment in MainFragment like this
getFragmentManager().beginTransaction().replace(R.id.main_frame, SampleFragment)
                           .addToBackStack(null).commit();
it crash with
android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()’ on a null object reference
       at android.support.v7.widget.RecyclerView.findMinMaxChildLayoutPositions(RecyclerView.java:3989)

and it happens even I replace with a blank fragment

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
