### ISSUE TITLE
Set custom fonts for HeaderItems and ImageCardView

### ISSUE THREAD

**Issue by HemangiVekaria** [googlesamples/androidtv-Leanback#130]
Hi , I am using BrowseSupportFragment for setting list rows with ImageCardView. Now i want to set custom font in my application but i am not able to set it using property android:fontFamily from style. Also not able to set custom fonts for xml file using android:fontFamily  Please help me. This is my first project in TV so i have no idea how to do this. Please help me .

**Comment by sohel274** [comment]
Same Question from my Side as per the @HemangiVekaria

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
