### ISSUE TITLE
Video As Background in the browse menu

### ISSUE THREAD

**Issue by acollazomayer** [googlesamples/androidtv-Leanback#132]
In the browse menu is it possible to add a video as background instead of the pictures.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
