### ISSUE TITLE
AndroidX migration issue

### ISSUE THREAD

**Issue by Veeresh8** [googlesamples/androidtv-Leanback#137]
We just moved to **AndroidX** and we are using the RowsSupportFragment, ArrayObjectAdapter to populate our rows. But somehow the **scroll is broken** where the first element is always snapped to the top. However, when we use the **android.support.v17.leanback** the scroll is fine.

Is this a known issue? Any workaround for this? We are in production

**Comment by evgentset** [comment]
Also have issue with RowsSupportFragment from **androidx.leanback.app**. 
Looks like scroll for first row (index = 0) is broken.
This works correctly : setSelectedPosition(0, false, ListRowPresenter.SelectItemViewHolderTask(3))
This does not work  : setSelectedPosition(2, false, ListRowPresenter.SelectItemViewHolderTask(3))

I don't want to get back to  **android.support.v17.leanback** , but IDK how to fix it. Any suggestions?

**Comment by marlonlom** [comment]
it seems that a way to deal with it is building the sample app from the beginning using androidx... i think is in another repo :(

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
