### ISSUE TITLE
How to change HeaderItem Font Style

### ISSUE THREAD

**Issue by ghost** [googlesamples/androidtv-Leanback#141]
Hello guys,
                 I need to change my headerItem font style.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
