### ISSUE TITLE
How to update json data on browseFragment?

### ISSUE THREAD

**Issue by darthdaniel16** [googlesamples/androidtv-Leanback#146]
Hi,

I am learning how to develop android tv apps and been using your code to help. I wanted to ask how can the data in the browseFragment be updated? For example if a new video is added (or changed) to the online json doc, how can the video information be updated? I read that **ArrayObjectAdapter** has an update method and also a **notifyItemRangeRemoved(0, itemCount)** call can be used but failed to find information on how the update script is called. How can I achieve this?

Also in line with the update, I also wanted to ask how the update is implemented if the json data is first stored in the db  then the data loaded from the db to the row displays?

Thanks

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
