### ISSUE TITLE
How to disable seekbar on PlaybackTransportControlGlue ?

### ISSUE THREAD

**Issue by mogylev** [googlesamples/androidtv-Leanback#148]
Hello
How can i desable seekbar on VideoPlayerGlue? VideoPlayerGlue is extends  PlaybackTransportControlGlue. Dodumentatios says that methods setSeekEnabled (false) should hide/disable  seekbar , but dont work.  
I tried      
mPlayerGlue!!.seekProvider = null
mPlayerGlue!!.isSeekEnabled = false
methods dont but nothing worked .
Help pls , how disable seekbar ?

**Comment by NereaElorza** [comment]
But can you reproduce your own videos in this example? I am trying it and the log said that there is a source error and that it could not access to the mp4 url. But the url that I am trying plays correctly in a pc browser

**Comment by mogylev** [comment]
I have a VideoSupportFragment child
in OnStart  method i init the player. I implemented player for online stream video.
   private fun initializePlayer() {
        val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory()
        mTrackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
        mPlayer = ExoPlayerFactory.newSimpleInstance(activity!!, mTrackSelector)
        mPlayerAdapter = LeanbackPlayerAdapter(activity, mPlayer, UPDATE_DELAY)
        mPlayerAdapter!!.setProgressUpdatingEnabled(false)
        mPlayerGlue = VideoPlayerGlue(activity!!, mPlayerAdapter!!, this)
        mPlayerGlue!!.seekProvider = null
        mPlayerGlue!!.isSeekEnabled = false
        mPlayerGlue!!.host = VideoSupportFragmentGlueHost(this)
        mPlayerGlue!!.playWhenPrepared()
}
in the documentation described that  method  isSeekEnabled = false  will disable seekbar on PlaybackTransportControlGlue (in my case VideoPlayerGlue ) if  seekProvider is null, but not working , seek bar alsways visible and duration changed

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
