### ISSUE TITLE
I can't play my own video

### ISSUE THREAD

**Issue by NereaElorza** [googlesamples/androidtv-Leanback#149]
I am trying to play my own videos in this app putting in PlaybackFragment.java line 178, in prepareMediaForPlaying(Uri.parse(...)) my own mp4 url and it doesn't work. I have an Source error and the log said that it couldn't access to this url. I know that the url that I am trying works properly, because I put it in a browser and it plays.

Could you help me please?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
