### ISSUE TITLE
Detail Fragment

### ISSUE THREAD

**Issue by aaghan** [googlesamples/androidtv-Leanback#150]
#150 ### Customization of Detail Fragment
#Question

Is there any way out to get detail fragment without only with STATE_FULL and actions focusable in the same state, hiding the STATE_HALF position of the fragment?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
