### ISSUE TITLE
How to customize BrowseFragment to show text and image preview above Row list

### ISSUE THREAD

**Issue by shekharbhadange-tudip** [googlesamples/androidtv-Leanback#151]
As we are new to the Android TV development and we are willing to design the screen as shown in the screenshot below.

After some sort of research on the Leanback library, came to know that we are supposed to use the BrowseFragment to achieve the expected result.

Now the problem is how to design the preview section in the top with a combination of Text and the Program poster as the BrowseFragment shows the Rows from the top left corner of the screen.

Do we need to use our customization or we can just use any of the Leanback library Fragment/Class/Activity?
![android_tv](https://user-images.githubusercontent.com/23417522/59928810-2aa77e00-945d-11e9-9c49-7d33201fc638.jpg)

**Comment by shekharbhadange-tudip** [comment]
Any update here?

**Comment by shekharbhadange-tudip** [comment]
Hey team, 
Can I get an update here?

**Comment by shekharbhadange-tudip** [comment]
Hey team, 
Can you please help me out here?

**Comment by dropedev** [comment]
actualización??

**Comment by shekharbhadange-tudip** [comment]
> actualización??

Meaning?

**Comment by dropedev** [comment]
también tengo ese tipo de inconveniente :)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
