### ISSUE TITLE
VerticalGridSupportFragment Focus Issue

### ISSUE THREAD

**Issue by PriyankaThakkar612** [googlesamples/androidtv-Leanback#152]
In VerticalGridSupportFragment, If I have 5 columns and number of items are 13, If the last item from the second row is selected, then on d-pad down click, Focus should go in the 3rd row.  How to do it? 

![Screenshot_1563863585](https://user-images.githubusercontent.com/40203041/61688274-36c77980-ad42-11e9-882f-5e58c8504c3c.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
