### ISSUE TITLE
It's possible to create a top navigation by using Leanback library in Android-TV

### ISSUE THREAD

**Issue by satishkumar-tudip** [googlesamples/androidtv-Leanback#153]
Hi Team, 
We are developing the one Android TV application using Leanback library and we wanted to design the Top navigation menu bar instead of the default Left side Menu bar provided by Leanback design.

I have Investigated to create a top navigation bar in android-tv by using Leanback library but I didn't find anything.

It is possible to create Top Navigation Menu bar using Leanback library.

**Comment by satishkumar-tudip** [comment]
![sling-tv-firestick-11](https://user-images.githubusercontent.com/22211700/63872993-60785e00-c9dc-11e9-8b74-50960ddad30d.jpg)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
