### ISSUE TITLE
Build fails with  "String types not allowed (at 'slideEdge' with value 'end')."

### ISSUE THREAD

**Issue by davidjashi** [googlesamples/androidtv-Leanback#22]
Tried Gradle 2.2.1 and 2.3 for the same result.

Full transcript of error message:

> What went wrong:
Execution failed for task ':app:processReleaseResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        c:\adt\sdk\build-tools\21.1.2\aapt.exe package -f --no-crunch -I c:\adt\sdk\platforms\android-21\android.jar -M C:\work\androidtv-Leanback-master\app\build\intermediates\manifests\full\release\AndroidManifest.xml -S C:\work\androidtv-Leanback-master\app\build\intermediates\res\release -A C:\work\androidtv-Leanback-master\app\build\intermediates\assets\release -m -J C:\work\androidtv-Leanback-master\app\build\generated\source\r\release -F C:\work\androidtv-Leanback-master\app\build\intermediates\res\resources-release.ap_ --custom-package com.example.android.tvleanback -0 apk --output-text-symbols C:\work\androidtv-Leanback-master\app\build\intermediates\symbols\release
Error Code:
        1
Output:
C:\work\androidtv-Leanback-master\app\build\intermediates\res\debug\transition-v22\lb_browse_entrance_transition.xml:23: error: Error: String types not allowed (at 'slideEdge' with value 'end').
C:\work\androidtv-Leanback-master\app\build\intermediates\res\debug\transition-v22\lb_browse_return_transition.xml:18: error: Error: String types not allowed (at 'slideEdge' with value 'start').
C:\work\androidtv-Leanback-master\app\build\intermediates\res\debug\transition-v22\lb_browse_return_transition.xml:27: error: Error: String types not allowed (at 'slideEdge' with value 'end').

**Comment by keyboardsurfer** [comment]
Thanks for the report. We're looking into it.
Internal: 19836282

**Comment by sandeep19** [comment]
I'm getting the same error. Is there any update on this bug?

**Comment by pengying** [comment]
I merged in an update for V22.  I wonder if the gradle dependecy Leanback-v17:+ was causing the issue.  It's compiling fine for me on mac.  Can you guys try again?

**Comment by davidjashi** [comment]
Thanks, now it works. By the way, is it OK, that I have to correct required Build Tools to currently available 22.0.1, as 22.0.0 is in no way available after ADT update?
