### ISSUE TITLE
androidtv-leanback-sample.png blocks building

### ISSUE THREAD

**Issue by Kusand** [googlesamples/androidtv-Leanback#26]
Went to run the sample code on Android Studio 1.1.0 and the build fails:

    Error:Error: Invalid file name: must contain only lowercase letters and digits ([a-z0-9_.])
    Error:Execution failed for task ':app:mergeDebugResources'.
    > /Users/eschra000/dev-work/androidtv-Leanback/app/src/main/res/drawable/androidtv-leanback-sample.png: Error: Invalid file name: must contain only lowercase letters and digits ([a-z0-9_.])

Renaming the file to use underscores fixes the issue. 5b966f1efdbcf5e2b3803331cf5fb3a82dbe868b deleted a file with this name, so I'm not sure if this file needs to be renamed or outright deleted.

**Comment by shawngit** [comment]
Fixed in the latest update.
