### ISSUE TITLE
Handling of KEYCODE_MEDIA_PLAY_PAUSE and other media remote buttons

### ISSUE THREAD

**Issue by tmack8001** [googlesamples/androidtv-Leanback#27]
According to the Android TV Design Guidelines in order to get an application accepted and published into Google Play an Android TV app that plays video or must content must respect the play/pause key during playback. This application doesn't handle any of the PLAY, PAUSE, or PLAY_PAUSE buttons on the PlaybackActivity.java and as a sample of an application that adheres to these guidelines an update should be made to bring this sample back into compliance with these published guidelines.

Please refer to our Media Play/Pause documentation for details:
http://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_MEDIA_PLAY_PAUSE

**Comment by shawngit** [comment]
I merged your pull request.  Thanks a lot!
