### ISSUE TITLE
All unclear things

### ISSUE THREAD

**Issue by FireFighter92** [googlesamples/androidtv-Leanback#37]
1. Working with UI (the Leanback library).
Specially for me it is difficult to understand which fragment is representing specific UI element, like where i can find list of fragments with associated xml layout? 
For example "ErrorFragment" how i will be able to know which layout structure it represents 

2. TvInputServices
What is the difference between TvInputService and standard android IntentService? As I know you can run IntentService from code but this situation is different with TvInputService. How TvInputService can be run or it is not necessary and it is enough to describe TvInputService in android manifest file?
How Android Live Channels app can recognize my TvInputService and run it? Can I сlose access Android Live Channels app to run my service without my permissions? Can i manipulate TvInputService from my app UI (ui with two buttons one of it should run service other one have to stop it)?

3. Authorization in Android Tv apps.
How many ways do we have to authorize users by social networks not only Google+ (Facebook, Twitter an etc)?
Ok. I have case and I spouse to build app which should has simple UI and a few TvInputService, but TvInputService must be run when current user already authorized.

**Comment by ryanseys** [comment]
Thanks for reporting your questions! 

1. The list of available Fragments is available on this page: https://developer.android.com/reference/android/support/v17/leanback/app/package-summary.html

For your example of `ErrorFragment`, you can see the XML attributes in the associated docs (you will have to click on the `[Expand]` link to expand): https://developer.android.com/reference/android/support/v17/leanback/app/ErrorFragment.html#inhattrs

![image](https://cloud.githubusercontent.com/assets/163873/8173496/0f8f9cec-1383-11e5-9d4e-9458aa8512f8.png)

2. Take a look at https://source.android.com/devices/tv/ if you want to try to add your own TV service. Perhaps someone else can comment on your questions here regarding the specifics, as at the current time, I don't know the answers to such specifics. Additionally, maybe the link I gave you can help answer those questions.

3. Android of course makes it easy to authorize with Google+ but for Facebook/Twitter/etc, you would have to implement your sign in flow yourself using the standard Android libraries. Leanback can of course help here with the UI but the sign in logic would exist independent of this.

Hope this helps! :)

**Comment by digitaldesaster** [comment]
regarding the authorization with other service you should think of a "second-screen" authorization like in the official youtube app. i think it is the best way for users. just generate a code and save it to a cloud database (like parse). point the user to a web interface, implement a standard authorization screen and save the tokens to the cloud database associated with the code....

**Comment by FireFighter92** [comment]
Thanks for your answer. I solved that problem with authorization. But now i
have another problem with type of stream, I know that there are a few
available types of stream for android tv like HLS *.m3u8 (HTTP Live
Streaming), HTTP Progressive *.mp4  and e.t.c.
For me i think HLS more approachable coz i have this link
http://vs2.cdn.ott.otautv.kz/dtv/id20_KTR_SG--7Kazakhstan/03/plst.m3u8, but
it doesn't work. When i was trying to pay this link i just could see blank
black screen and also i have  other link
http://auth.torrent-tv.ru/h/719/1/2/WWdKN0pSWFpoMVVYU09PUExtOHc4Z1Y4d3FDd1JDUk5jTnV0am16UURINEViYTRGZVlRV3ppWDk1Z3NmYkhlVA
and it doesn't  work too. I have tried many times with many type of stream
and nothing :(( Maybe i should do something with stream before?

2015-06-21 20:20 GMT+06:00 Alex <notifications@github.com>:

> regarding the authorization with other service you should think of a
> "second-screen" authorization like in the official youtube app. i think it
> is the best way for users. just generate a code and save it to a cloud
> database (like parse). point the user to a web interface, implement a
> standard authorization screen and save the tokens to the cloud database
> associated with the code....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/androidtv-Leanback/issues/37#issuecomment-113907447>
> .
>



-- 

*С уважением,Lyssenko Artem: artem.lysenko92@gmail.com
<Aartem.lysenko92@gmail.com>*

**Comment by ryanseys** [comment]
@FireFighter92 I've updated the sample to include support for ExoPlayer. Though out of the box this won't allow you to point it at an HLS stream, it should be very easy to add if you look at our sample code along with the [ExoPlayer demo app](https://github.com/google/ExoPlayer/tree/master/demo), and specifically their [`HlsRendererBuilder`](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java).

Hope this helps!
