### ISSUE TITLE
programmatically set the scroll position of a browsefragment

### ISSUE THREAD

**Issue by digitaldesaster** [googlesamples/androidtv-Leanback#38]
as discussed here

https://plus.google.com/101881632463511791527/posts/BBHAS7JVXjn

**Comment by digitaldesaster** [comment]
feedback from John Butterfield:

The RowsFragment is the container of rows, setting selected position there is like telling which row to be selected. To tell it which item you want selected, it seems like right now you need to drill down into the innards of the row to do this. You would call the same function (setSelectedPosition[Smooth]) when you access the "VerticalGridView" used internally for the row of items. 

You can work around this, but it's not pretty.  Also this won't have all the hooks the system needs to ensure things are kept within scroll boundaries, so if causing this item to focus changes it's size it won't necessarily keep it scrolled on screen. Here's some code from Dake, which I've revised a little for clarity:

Use a subclass of RowsFragment which can get the vertical listview:

RecyclerView listView = (RecyclerView) findGridViewFromRoot();

Then drill in like so:

View view = listView.findViewByPosition(1);  // might be null if view
is not scrolled in position
ItemBridgeAdapter.ViewHolder ibvh = (ItemBridgeAdapter.ViewHolder)
listView.getChildViewHolder(view);
ListRowPresenter rowPresenter = (ListRowPresenter) ibvh.getPresenter();

// get the internal view holder of the row's VerticalGridView, which is currently what's used to do the linear layout of cards.
ListRowPresenter.ViewHolder vh = (ListRowPresenter.ViewHolder)
rowPresenter.getRowViewHolder(ibvh.getViewHolder());

// finally call the intended set selected position on the correct grid view
vh.getGridView().setSelectedPositionSmooth(xyz);

Final note: We are aware of this being pretty crummy. I am working on some stuff right now which I hope will improve this situation. And we filed a bug to handle this more gracefully with the RowsFragment.﻿

**Comment by mustafasevgi** [comment]
View view = listView.findViewByPosition(1);    view is always null.

**Comment by ch-muhammad-adil** [comment]
Hey I am using Subclass of BrowseFragment ..  How can I use RowsFragment in that ???

**Comment by ch-muhammad-adil** [comment]
I want to add nested scrolling like if user goes to the last item towards right side in a row then when it press further right key then user should start from the first one.

**Comment by ch-muhammad-adil** [comment]
Any help Please ?

**Comment by PhatJo** [comment]
@ch-muhammad-adil  see http://stackoverflow.com/questions/29995318/scroll-to-given-position-in-android-leanback-listrow/37878060#37878060

**Comment by ch-muhammad-adil** [comment]
@PhatJo  Thanks man. Actually I have resolved this issue and it was a lot easier than my expectations.

**Comment by astuter** [comment]
@ch-muhammad-adil Can you share your solution or tell us how can we achieve this? as mentioned SO answer  

`setSelectedPosition(0, true, new ListRowPresenter.SelectItemViewHolderTask(lastVideoPosition));`

causing java.lang.IllegalStateException: Cannot start headers transition.

**Comment by vldmkr** [comment]
@astuter Just call setSelectedPosition(...) on RowsFragment of your BrowseFragment:
```
mBrowseFragment.getRowsFragment().setSelectedPosition(0, true, new ListRowPresenter.SelectItemViewHolderTask(lastVideoPosition));
```

**Comment by astuter** [comment]
@vldmkr Thanks a lot. Calling this method on RowsFragment did the trick :)

**Comment by ch-muhammad-adil** [comment]
is this worked for you ?

**Comment by astuter** [comment]
@ch-muhammad-adil 👍  Yes it worked. Seems perfect solution for this.

**Comment by MayankSoni** [comment]
Can you please share me with source code. I'm stuck last few days. Please guys anyone have you any idea please share with me. mayanklangalia@gmail.com
