### ISSUE TITLE
Long Press for Item in browsefragement

### ISSUE THREAD

**Issue by digitaldesaster** [googlesamples/androidtv-Leanback#39]
Please think about implementing a long press event. This could be useful to show a quick Dialog to the user to select an option. for example. 

longpress on an album cover: instead of playing the album it could be 
liked, saved to library, browsed, etc....

**Comment by ryanseys** [comment]
We have requested this functionality from the Leanback eng team internally. I agree it would be a nice feature.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
