### ISSUE TITLE
Use of MediaSessionCompat in Support Library

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/androidtv-Leanback#41]
Migrate the code using MediaSession to MediaSessionCompat, so that the application can run on pre-lollipop devices.

Since this app is to demo Leanback support library of v17, running on sdk21+ should not be a requirement.

**Comment by ryanseys** [comment]
Hi @seventhmoon I see where you are coming from regarding v17 support. We've decided to try to keep the Leanback sample as **lean** (heh) and simple as possible for new developers, which also continuing to showcase a number of features related to Android TV such as recommendations, the Now Playing card, and Voice Search. So although using MediaSessionCompat is totally possible when building your app for your users, we prefer to keep this sample up to date with the latest APIs for simplicity sake. Hope you understand this justification.

**Comment by seventhmoon** [comment]
I am confused.

Shall I consider this "Leanback Support Library Sample" a "Android TV Sample Application"?

According to the project name and the README.md, I think this project is a sample of the leanback support library (minSdk=17) rather than a Android TV Sample application (minSdk=21).

**Comment by ryanseys** [comment]
@shawngit What do you think?

**Comment by seventhmoon** [comment]
Some more information.
In I/O 2015, I asked a similar question about the leanback support library.

I think this lib is to help developer to make a UI for TV. This TV is not limited to Android TV.

There are numbers of Android STB (e.g. Amazon Fire TV, XiaoMi MiBox, etc) and they are not Android TV. 

Leanback support lib should be able to run on these platforms (as it only require minSdk=17). Googler also says yes during I/O.

So, shall we have a another Leanback support library sample if this is targeting for Android TV?

**Comment by ryanseys** [comment]
I believe the focus of this library is Android TV and is though it may work with other TVs, they aren't being tested against this library. I believe the name of the repo and description in the README make this particularly clear:

> The Leanback API Demo/Videos By Google app is designed to run on an **Android TV device**. It demonstrates how to use the Leanback Support library to develop **Android TV** apps with user friendly UI that will comply with the UX guidelines of **Android TV**.

**Comment by philipgiuliani** [comment]
Is somewhere on Github a example how to use `MediaSessionCompat`? I can't get it working with the latest android tv support library.
