### ISSUE TITLE
Action not showing icon

### ISSUE THREAD

**Issue by thailemon** [googlesamples/androidtv-Leanback#47]
Adding Action() in DetailsOverviewRow 
using either DetailsOverviewRow.addAction() or DetailsOverviewRow.setActionAdapter()
is NOT showing the icon using new Action(label1, label2, drawable)

**Comment by Fleker** [comment]
Hey @thailemon are you still seeing this issue?

**Comment by thailemon** [comment]
No, I thankfully didn't wait for a response and fixed the issue back then. :)
