### ISSUE TITLE
Deeplink stops working

### ISSUE THREAD

**Issue by anhtuannd** [googlesamples/androidtv-Leanback#48]
I tried to search for Noah to see deep linking, however search result displayed as normal.
I'm using Nexus Player, Android 6.0.

**Comment by ryanseys** [comment]
Not sure what you mean by "normal", can you please explain what you see vs. what you expect to see? A screenshot may help.

**Comment by anhtuannd** [comment]
I found out that Google Play Movies & TV is not available for my country. Maybe it's reason why this issue happens.

**Comment by Fleker** [comment]
Hey @anhtuannd are you still seeing this issue?

**Comment by anhtuannd** [comment]
It works normally right now. Also, I can access to Google Play Movies & TV.
