### ISSUE TITLE
ErrorFragment causes crash

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/androidtv-Leanback#53]
Hello,
every time I click on ErrorFragment, the app crashes.  Here is the stacktrace:
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.tvleanback/com.example.android.tvleanback.ui.BrowseErrorActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f1000ce (com.example.android.tvleanback:id/main_frame) for fragment ErrorFragment

Please advise.

**Comment by IgorGanapolsky** [comment]
Anyway, I believe I fixed this crash in the pull request: https://github.com/googlesamples/androidtv-Leanback/pull/54

**Comment by ryanseys** [comment]
Fixed in 626f223d6d34abcf581bd7c09f225b9aba0ab3d1
