### ISSUE TITLE
Does not work in android TV emulator 

### ISSUE THREAD

**Issue by fragalles** [googlesamples/androidtv-Leanback#55]
does not work in android TV emulator 720p and 1080p mode.
latest android 6.0 latest studio sdk 
the emulator shows only a gray "Android" text but nothing happens

:app:assembleDebug
BUILD SUCCESSFUL
Total time: 3 mins 35.472 secs

**Comment by ryanseys** [comment]
Duplicate of #50

**Comment by IgorGanapolsky** [comment]
#50 is not even resolved.
