### ISSUE TITLE
Voice search button cannot be selected

### ISSUE THREAD

**Issue by Armaxis** [googlesamples/androidtv-Leanback#60]
I encountered a bug while using the demo app. Steps to reproduce:
1. Launch app, go to Search Activity
2. Type in (or dictate) something in search, that will result in no results (some gibberish like "asjkdhasdha") will work just fine.
3. Try to select the "Voice search button" with D-Pad. It will be impossible. The only way to go from there is only by selecting the search text input and typing or clearing up the search query. 

I suspect the issue happens because when there are no results what we actually do is add a new row to adapter with Header and no items:
```
example\ui\SearchFragment.java
...
} else {
    // No results were found.
    mRowsAdapter.clear();
    HeaderItem header = new HeaderItem(getString(R.string.no_search_results, mQuery));
    ListRow row = new ListRow(header, new ArrayObjectAdapter());
    mRowsAdapter.add(row);
}
```

This triggers the focus to be set on the first row (because `mResultAdapter.size() > 0` is `true`, since adapter has one row) and therefore breaks the focus, so it is no longer possible to select "Voice search" button. 

```
v17.leanback.app.SearchFragment.java
private void updateFocus() {
        if (mResultAdapter != null && mResultAdapter.size() > 0 &&
                mRowsFragment != null && mRowsFragment.getAdapter() == mResultAdapter) {
            focusOnResults();
        } else {
            mSearchBar.requestFocus();
        }
    }
```

**Comment by GeoffreyEmery** [comment]
still a bug search is broken
