### ISSUE TITLE
PIP branch not working

### ISSUE THREAD

**Issue by GeoffreyEmery** [googlesamples/androidtv-Leanback#65]
Seems to not show on any of the builds

**Comment by ryanseys** [comment]
Can you clarify this? Are you seeing an error message? Let me know how I can help further to resolve this issue.

**Comment by GeoffreyEmery** [comment]
the app-pip branch contains no pip

**Comment by ryanseys** [comment]
Look at https://github.com/googlesamples/androidtv-Leanback/pull/66

**Comment by GeoffreyEmery** [comment]
you can close
