### ISSUE TITLE
Custom Cards are invisible...  

### ISSUE THREAD

**Issue by ch-muhammad-adil** [googlesamples/androidtv-Leanback#67]
I have used a custom card which is a subclass of BaseCardView. You can see the hidden row was third row and it was not inside the screen but when I scroll and it shows up hidden. Why it is not visible ? 
![screen shot 2016-05-07 at 1 40 51 pm](https://cloud.githubusercontent.com/assets/8264639/15091178/ce372f3e-1459-11e6-80c7-e49c2ab1c877.png)
![screen shot 2016-05-07 at 1 40 27 pm](https://cloud.githubusercontent.com/assets/8264639/15091179/d6fe99a4-1459-11e6-8097-bd7494ee3972.png)

**Comment by Fleker** [comment]
Hey @ch-muhammad-adil are you still seeing this issue?

**Comment by ch-muhammad-adil** [comment]
Yes last time when i stoped working on this I wasn't able to solve this
issue.

**Comment by Fleker** [comment]
Okay can you post some code snippets for your Card class and presenter?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
