### ISSUE TITLE
 can add support play HLS video and VTT subtitle

### ISSUE THREAD

**Issue by qoo888** [googlesamples/androidtv-Leanback#68]
can add support play HLS video and VTT subtitle?
thank you..

**Comment by ryanseys** [comment]
HLS video and WebVtt subtitles are already supported by using [ExoPlayer](https://github.com/google/ExoPlayer/) to play videos in this sample. Please see that library for more information for the supported formats.

**Comment by qoo888** [comment]
i tested ExoPlayer demo play hls ok, but this androidtv-Leanback cannot play .
change ExoPlayer demo code play mp4 load vtt  subtitle work, 
change this androidtv-Leanback code no display subtitle :(
did recommends sample code display subtitle (mp4+ vtt) very need, 
thank you enough..

**Comment by ryanseys** [comment]
Take a look at our other sample if you'd like to view subtitles. https://github.com/googlesamples/androidtv-sample-inputs/tree/master/app/src/main/java/com/example/android/sampletvinput/player

ExoPlayer implementation details are beyond the scope of this sample but I hope the code you find here will help you resolve your issue.

**Comment by qoo888** [comment]
ok....les't me try, thank you.
