### ISSUE TITLE
Custom Fragment

### ISSUE THREAD

**Issue by YuckFo** [googlesamples/androidtv-Leanback#69]
Hi,
is there any way how to add custom fragment (for example EPG) when I select something in left navigation menu ?
Thx for advice.

**Comment by Fleker** [comment]
I believe you should be able to override the click listener in your custom [header fragment](https://github.com/googlesamples/androidtv-Leanback/blob/master/app/src/main/java/com/example/android/tvleanback/presenter/IconHeaderItemPresenter.java) to do a behavior on the selected `ViewHolder`.

**Comment by MayankSoni** [comment]
Hello Friends, I have custom fragment inside recyclerview with customized button and other controller. 
I have focus issue if im trying to press down key focus is working but if im trying to press up key focus not move to top. Please help me for the same. I have extend (fragment) with custom view.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
