### ISSUE TITLE
playbackOverlayfragment is coming at center of the activity

### ISSUE THREAD

**Issue by vishnuganta22** [googlesamples/androidtv-Leanback#71]
Updated the leanback_support library to version 24.0.0 from then the playback_overlay_fragment is positioned at center of the activity
![vod](https://cloud.githubusercontent.com/assets/15953004/16377610/aced6854-3c84-11e6-8baf-08d60a8d609b.png)

**Comment by Fleker** [comment]
Is that running on a tablet?

**Comment by vishnuganta22** [comment]
It is same with the androidtv too

**Comment by Fleker** [comment]
What does it look like when you use the previous version (`23.4.0`?) I don't see any change with this Leanback Sample app using the current version of the Leanback support library on an Android TV.

![instantupload](https://cloud.githubusercontent.com/assets/3291635/16423983/1611bf4a-3d13-11e6-8723-8e5af46bcd97.png)

**Comment by benbaxter** [comment]
@vishnuganta22 Can you recreate the issue still? 

Note that the sample has been updated to 26.0.1 and the PlaybackOverlayFragment has been deprecated. The new implementation with VideoFragment and PlaybackTransportControlGlue has an improved display for the playback controls.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
