### ISSUE TITLE
androidtv-Leanback view bug

### ISSUE THREAD

**Issue by phcycat** [googlesamples/androidtv-Leanback#74]
Without making any modifications to create a duplicate VIEW found not recycled to create an overlay

**Comment by Fleker** [comment]
Hi. Can you elaborate? If there's a visual issue can you post a screenshot?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
