### ISSUE TITLE
How can I customize browsefragement?

### ISSUE THREAD

**Issue by LLin233** [googlesamples/androidtv-Leanback#75]
Hello, 
Recently, I would need some layout changing in my App like call showTitle() in BrandedFragment, but I could not do it from MainFragment that extends BrowseFragment since it's not public.

May I ask how can I tone it a little bit to adapt my design? Mainly about how to hide title/badge layout and put badge on the headerDrawerDrawer.

Thank you in advanced for your help!

**Comment by Fleker** [comment]
You can extend these Leanback classes with your own implementation. You can
also extend themes.

**Comment by LLin233** [comment]
I am trying to control the visibility of the layout shows badge. 
When the Sidebar shows, badge layout shows, otherwise the layout will be hidden so that it doesn't leave the margin on the top. 

I saw a showTitle() method on the superclass, but it looks like just running the animation instead changing the layout. so I am stuck.

I really appreciate your help.

**Comment by Fleker** [comment]
I looked into some of this today and I found a few ways that you can modify these properties in your app while only changing code in your `MainFragment`. 

### Hide Title / Badge
This can be done just by not setting these items. From `MainFragment.setupUIElements`:
  
    //        setBadgeDrawable(
    //                getActivity().getResources().getDrawable(R.drawable.videos_by_google_banner, null));
    //        setTitle(getString(R.string.browse_title)); // Badge, when set, takes precedent over title\

### Put badge on HeaderDrawer
You can do this by overwriting the search orb. Right now the implementation still does a search when you click and grows when focused.

    @Override
    public void onResume() {
        super.onResume();
        ((ImageView) getActivity().findViewById(R.id.icon)).setImageDrawable(getResources().getDrawable(R.drawable.ic_main_icon));
        getActivity().findViewById(R.id.search_orb)).setBackgroundColor(getResources().getColor(android.R.color.transparent);
    }

You can extend the `SearchOrbView` class and override `onFocusChanged` and `setOnOrbClickedListener` to remove the standard behavior.

### Remove the top margin
If you want to remove the top margin, override this item in your `dimens.xml` file. It doesn't look too good though, so you may need to do a lot of additional tweaking.

    <dimen name="lb_browse_rows_margin_top">64dp</dimen>

**Comment by LLin233** [comment]
Thank you!
The margin overriding is so helpful. By the way, since I can't get the 'layoutparams' from the BrowseFragment, how do I set the margin programmably?

**Comment by Fleker** [comment]
That would be difficult. All of the positioning occurs in the [BrowseFragment](https://android.googlesource.com/platform/frameworks/support/+/master/v17/leanback/src/android/support/v17/leanback/app/BrowseFragment.java) 

You'd have to replace the `mContainerListAlignTop` with some dynamic value and update it. You can see how it is set in the `onStart` method:

    @Override
    public void onStart() {
        super.onStart();
        mHeadersFragment.setWindowAlignmentFromTop(mContainerListAlignTop);
        mHeadersFragment.setItemAlignment();
        mRowsFragment.setWindowAlignmentFromTop(mContainerListAlignTop);
        mRowsFragment.setItemAlignment();
        mRowsFragment.setScalePivots(0, mContainerListAlignTop);
    }

**Comment by SunilpRathod** [comment]
How can i customize sidebar in androidtv-leanback
