### ISSUE TITLE
re-sizing the custom cardview inherits from BaseCardView with wrap-content height

### ISSUE THREAD

**Issue by LLin233** [googlesamples/androidtv-Leanback#81]
Hi,

I recently ran into a problem that needs to resize the height of `cardview` in `PlaybackOverlayFragment` after the `TextView` has been set with the text.

`setText()` was binding in `onBindViewHolder()`

 I gave the layout of view fixed width and the height is set to `wrap_content`, but after I have set the text and attempt to call `requestLayout()` or `invalidate ()`, I am not able to re-size the card.

may I ask your opinion that how to achieve it?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
