### ISSUE TITLE
Custom Header Stopped Scrolling

### ISSUE THREAD

**Issue by awaistariq** [googlesamples/androidtv-Leanback#82]
After updating gradle and android libraries to latest, Custom Header Scrolling stopped completely.
onSelectLevelChanged is not getting called.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
