### ISSUE TITLE
MobileWelcomeActivity is opening in TV 

### ISSUE THREAD

**Issue by rameshkec85** [googlesamples/androidtv-Leanback#83]
I have installed apk in Android TV (mbox) but  MobileWelcomeActivity is opening instead of MainActivity

**Comment by tomas-paronai** [comment]
@rameshkec85 This happened to me few times on emulator and on some android tv boxes. I have worked this around by checking in the on create method of the mobile activity if it is a television or not. If it is, than I start the tv activity and finish current.
You can add values-television resource, where yo ucan add boolean for television true and for mobile false. Than you just get them in the activity.

**Comment by Fleker** [comment]
Which Android TVs is that happening on? Where do you open these apps from?

**Comment by tomas-paronai** [comment]
@Fleker In my case this only happened when I launched the app from android studio on emulator. I had two different launcher activities defined in manifest, one for mobile and one for leanback. When I reopened app from launcher it launched the correct one. 
I know this was happening on some TV devices from crash reports of app usage, there were some different app features for mobile app version.

**Comment by Fleker** [comment]
In the emulator, I believe Android studio defaults to launching the launch
activity and never to the leanback activity unless specified.

**Comment by wuqingwei** [comment]
I solved this problem by lanching the app form Setting-> Installed applications
FYI.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
