### ISSUE TITLE
Headers Fragment

### ISSUE THREAD

**Issue by viktordolgalyov** [googlesamples/androidtv-Leanback#84]
Is Leanback has default possibility to make HeadersFragment non scrollable like it implemented in the Google Play Store?

**Comment by sohow** [comment]
I have the same problem too

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
