### ISSUE TITLE
App doesn't keep playback behind leanback launcher if "Recent" is pressed in Android >= 7.

### ISSUE THREAD

**Issue by JesusM** [googlesamples/androidtv-Leanback#87]
Tested on an NVIDIA SHIELD device running Android 7.0

These are the steps to reproduce the issue:
 - Start video playback.
 - Hit "Recent" button.
 - Return to the app from app switcher. Video player was closed and item's preplay screen is displayed.
 - Play item again.
 - Hit "Home" button.

Expected behaviour:
- App should keep video playback in leanback launcher background.

Actual behaviour:
- Video playback is stopped.

This happens because when "Recents" button is hit, `PlaybackOverlayFragment:onPause` is calling `getActivity().requestVisibleBehind(true)` so it's saying app wants to stay behind which I think it's not correct, as the system displays app switcher rather than leanback launcher so there is no point leaving video playback behind that UI. When playback is started again after returning to the app via app switcher and then "Home" is hit, `requestVisibleBehind` is again called but system is returning `false` this time, forcing video playback to be stopped.

Is there a way to identify that "Recents" button is hit and therefore don't request to leave video playback behind? 

In this video you can see the behaviour described: https://drive.google.com/file/d/0B3_15qFiB8KVT1V1b3VPVEp5c28/view?usp=sharing

**Comment by Fleker** [comment]
AFAIK the app only gets the onPause event, but doesn't know why it received
that event. I can see what you mean by that issue, so I think the app would
have to better adapt to be more resilient to different types of pausing.

**Comment by JesusM** [comment]
> I can see what you mean by that issue, so I think the app would
have to better adapt to be more resilient to different types of pausing.

I see, but how? I'm sure I'm missing something but I don't see how the app can check what was the cause of it being paused (to identify when it was due to Home or Recent button)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
