### ISSUE TITLE
OnItemViewClickedListener not working  "RowsFragment"

### ISSUE THREAD

**Issue by dinhhieuac** [googlesamples/androidtv-Leanback#88]
Hi Dev
use : com.android.support:leanback-v17:25.3.1 
some item "OnItemViewClickedListener " not working 

use : com.android.support:leanback-v17:25.0.1
work normal
Thanks
HieuHD

**Comment by inv3rse** [comment]
It is an issue in the support library: https://issuetracker.google.com/issues/37488223
25.2.0 works fine as well

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
