### ISSUE TITLE
Data does not load in opening the app on Android Fire TV

### ISSUE THREAD

**Issue by khat33b** [googlesamples/androidtv-Leanback#89]
While running the app, the main screen appears with a large loading circle. The data never loads and none of the buttons work. Only the Voice search option works. I am running in Amazon Fire TV. The OS is Fire OS 5.2.4.1 and the Fire TV Home Version is 5.7.3-17.

**Comment by ericharlow** [comment]
I also tried running this app on an Amazon FireTv just to see what happens. I got the same results as @khat33b. I started up the debugger and noticed MainFragment.onAttach(Context) is not called on the firetv.  I then realized that onAttach(Context) is an api 23 call. Firetv is running on api 22. 

if you want a quick and dirty way to see the browse fragment show on the firetv just add
```
@Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);

        // Create a list to contain all the CursorObjectAdapters.
        // Each adapter is used to render a specific row of videos in the MainFragment.
        mVideoCursorAdapters = new HashMap<>();

        // Start loading the categories from the database.
        getLoaderManager().initLoader(CATEGORY_LOADER, null, this);
    }
```
 to the MainFragment.

**Comment by tonespy** [comment]
It really isn't dirty. You can do something like this too
```
@RequiresApi(23)
    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        attachedToView();
    }

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        attachedToView();
    }

    private void attachedToView() {

        // Create a list to contain all the CursorObjectAdapters.
        // Each adapter is used to render a specific row of videos in the MainFragment.
        mVideoCursorAdapters = new HashMap<>();

        // Start loading the categories from the database.
        getLoaderManager().initLoader(CATEGORY_LOADER, null, this);
    }
```
@ericharlow

**Comment by dpreussler** [comment]
this would execute attachedToView twice though as RequiresApi is just a marker interface

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
