### ISSUE TITLE
leanback-library: 25.+: BackgroundManager loses background when going back from DatailsFragment to MainFragment

### ISSUE THREAD

**Issue by ad-on-is** [googlesamples/androidtv-Leanback#90]
Let's say we have two fragments. MainFragment showing a ListRow of card-items and the DetailFragment that opens when a card is clicked.
- When a card is selected, the background of MainFragment get set according to the bgImagUrl.
- When a card is clicked, the background of DetailsFragment is also set.
- When leaving DetailsFragment and going back to MainFragment the background fades out and there's no background-image on the MainFragment.

I tried calling updateBackground() in `onResume()` of MainFragment, but the result is, that the background fades out, and fades back in.

The behaviour of leanback-library:24 was:
- When leaving DetailsFragment and going back to MainFragment, the background was still there.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
