### ISSUE TITLE
Search Hint Location

### ISSUE THREAD

**Issue by minhjirachi** [googlesamples/androidtv-Leanback#91]
Hello,

I want to make the search hint like the below image:

http://imgbox.com/BjBcuXrG

Anyone please tell me how to make that hint?

Thank you

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
