### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by CatKaiserGIT** [googlesamples/androidtv-Leanback#97]
I'm not sure whether it is an android OS error or application, but when I type something in the Android OS, such as "New dad" keyword to find something from the app's database the search of Android OS does not show suggestions, it is showing "collecting additional results from 0 of 1 apps".

Can you please check this issue?

**Comment by benbaxter** [comment]
This sounds like an OS/Search issue if it is happening from the home screen. We just launched the Google Assistant on Android TV (released on Nvidia shields last week) which has a bunch of updates to search, so hopefully this is a non-issue after the roll out.

What did you produce this behavior on? Which version of Android were you running?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
