### ISSUE TITLE
Official ExoPlayer implementation of PlayerAdapter in Leanback Library

### ISSUE THREAD

**Issue by mkjensen** [googlesamples/androidtv-Leanback#99]
I'm not sure how to contact the authors of [v17 Leanback Library](https://developer.android.com/topic/libraries/support-library/packages.html#v17-leanback).

I have requested an official [ExoPlayer](https://github.com/google/ExoPlayer) implementation of [PlayerAdapter](https://developer.android.com/reference/android/support/v17/leanback/media/PlayerAdapter.html).

See https://github.com/google/ExoPlayer/issues/3382 for more details.

**Comment by mkjensen** [comment]
I also added the issue at https://github.com/googlesamples/leanback-showcase/issues/45.

**Comment by mkjensen** [comment]
There is already an implementation at https://github.com/google/ExoPlayer/tree/dev-v2/extensions/leanback. Sorry for the noise.

**Comment by srinivasgoud** [comment]
Hi mkjensen ,

Can you please guide me that for Remote Return button handling in Exoplayer,

best Regards, 
srinivas
